(function registerEnemyStageBalance(root) {
  const scope = root.RXGame || (root.RXGame = {});
  const STAGE_STRUCTURE_CONFIG = { prologueChapterIndex: 0, prologueStageCount: 3, minChapterIndex: 1, maxChapterIndex: 9, normalStageCount: 10, battleEndSeconds: 90, bossAppearSeconds: 60 };
  const CHAPTER_ENEMY_FIRE_INTERVAL_BASE = { 1: 1, 2: .9, 3: .8, 4: .7, 5: .65, 6: .6, 7: .55, 8: .5, 9: .45 };
  const ENEMY_FIRE_INTERVAL_LIMIT = { minNormalFireInterval: .35, minBurstFireInterval: .1 };
  const ENEMY_TYPE_CONFIG = {
    small: { id: "small", name: "小型敌机", baseHp: 100, baseDamage: 8, moveSpeed: 140, canFire: true, firstFireDelay: .4, fireIntervalMultiplier: 1.2, bulletSpeed: 260, bulletPattern: "single" },
    shooter: { id: "shooter", name: "射击敌机", baseHp: 160, baseDamage: 10, moveSpeed: 115, canFire: true, firstFireDelay: .3, fireIntervalMultiplier: 1, bulletSpeed: 300, bulletPattern: "triple" },
    charger: { id: "charger", name: "高速突击敌机", baseHp: 140, baseDamage: 18, moveSpeed: 220, canFire: false, firstFireDelay: null, fireIntervalMultiplier: null, bulletSpeed: null, bulletPattern: "none" },
    shield: { id: "shield", name: "护盾敌机", baseHp: 220, baseDamage: 10, moveSpeed: 90, canFire: true, firstFireDelay: .8, fireIntervalMultiplier: 1.1, bulletSpeed: 260, bulletPattern: "single", extraDamageReductionRate: .15 },
    elite: { id: "elite", name: "精英战机", baseHp: 1000, baseDamage: 18, moveSpeed: 80, canFire: true, firstFireDelay: .6, fireIntervalMultiplier: .8, bulletSpeed: 330, bulletPattern: "spread" },
    boss: { id: "boss", name: "BOSS战机", baseHp: 10000, baseDamage: 25, moveSpeed: 55, canFire: true, firstFireDelay: 1, fireIntervalMultiplier: .7, bulletSpeed: 360, bulletPattern: "boss_spread" }
  };
  const BOSS_BURST_ATTACK_CONFIG = { fireInterval: .1, duration: 2, cooldown: 8, triggerHpRates: [.7, .4, .15], bulletPattern: "boss_burst_spread" };
  const PROLOGUE_STAGE_CONFIG = { 1: { difficultyBonus: 0, enemyCount: 18, composition: { small: 1, shooter: 0, charger: 0, shield: 0, elite: 0 } }, 2: { difficultyBonus: 0, enemyCount: 24, composition: { small: .9, shooter: .1, charger: 0, shield: 0, elite: 0 } }, 3: { difficultyBonus: 0, enemyCount: 30, composition: { small: .85, shooter: .15, charger: 0, shield: 0, elite: 0 } } };
  const STAGE_DIFFICULTY_TEMPLATE = { 1: 0, 2: .02, 3: .04, 4: .06, 5: .12, 6: .14, 7: .16, 8: .18, 9: .2, 10: .32 };
  const BASE_STAGE_ENEMY_COUNT_TEMPLATE = { 1: 30, 2: 34, 3: 38, 4: 42, 5: 48, 6: 50, 7: 54, 8: 58, 9: 62, 10: 55 };
  const STAGE_COMPOSITION_TEMPLATE = { grass: { small: .8, shooter: .2, charger: 0, shield: 0, elite: 0 }, gate: { small: .6, shooter: .25, charger: .1, shield: 0, elite: .05 }, pressure: { small: .5, shooter: .25, charger: .1, shield: .1, elite: .05 }, boss: { small: .4, shooter: .25, charger: .1, shield: .1, elite: .15 } };
  const CHAPTER_7_STAGE_DAMAGE_REDUCTION = { 1: .45, 2: .48, 3: .5, 4: .52, 5: .58, 6: .6, 7: .62, 8: .65, 9: .68, 10: .7 };
  const CHAPTER_7_COMPOSITION_OVERRIDE = { 1: { small: .45, shooter: .25, charger: .1, shield: .1, elite: .1 }, 2: { small: .45, shooter: .25, charger: .1, shield: .1, elite: .1 }, 3: { small: .42, shooter: .25, charger: .1, shield: .13, elite: .1 }, 4: { small: .4, shooter: .25, charger: .1, shield: .15, elite: .1 }, 5: { small: .35, shooter: .25, charger: .1, shield: .2, elite: .1 }, 6: { small: .32, shooter: .25, charger: .1, shield: .23, elite: .1 }, 7: { small: .3, shooter: .25, charger: .1, shield: .25, elite: .1 }, 8: { small: .28, shooter: .25, charger: .1, shield: .27, elite: .1 }, 9: { small: .25, shooter: .25, charger: .1, shield: .3, elite: .1 }, 10: { small: .2, shooter: .25, charger: .05, shield: .3, elite: .2 } };
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const getStageId = (chapterIndex, stageInChapter) => chapterIndex === 0 ? `prologue_${stageInChapter}` : `${chapterIndex}_${stageInChapter}`;
  function getPreviousStageId(chapterIndex, stageInChapter) { if (chapterIndex === 0 && stageInChapter === 1) return null; if (chapterIndex === 0) return getStageId(0, stageInChapter - 1); if (chapterIndex === 1 && stageInChapter === 1) return getStageId(0, 3); return stageInChapter === 1 ? getStageId(chapterIndex - 1, 10) : getStageId(chapterIndex, stageInChapter - 1); }
  const isStageUnlocked = ({ chapterIndex, stageInChapter, clearedStageIds }) => { const previous = getPreviousStageId(chapterIndex, stageInChapter); return previous === null || (clearedStageIds || []).includes(previous); };
  const getChapterDifficultyBase = (chapterIndex) => chapterIndex <= 1 ? 0 : (chapterIndex - 1) * .12;
  const getStageTemplateType = (stageInChapter) => stageInChapter <= 4 ? "grass" : stageInChapter === 5 ? "gate" : stageInChapter <= 9 ? "pressure" : "boss";
  const getStageDifficulty = (chapterIndex, stageInChapter) => chapterIndex === 0 ? (PROLOGUE_STAGE_CONFIG[stageInChapter]?.difficultyBonus || 0) : getChapterDifficultyBase(chapterIndex) + (STAGE_DIFFICULTY_TEMPLATE[stageInChapter] || 0);
  const getStageDamageReductionRate = (chapterIndex, stageInChapter) => chapterIndex === 0 ? 0 : chapterIndex === 7 ? (CHAPTER_7_STAGE_DAMAGE_REDUCTION[stageInChapter] || .45) : clamp(getStageDifficulty(chapterIndex, stageInChapter) * .5, 0, .65);
  const getStageEnemyHpMultiplier = (chapterIndex, stageInChapter) => 1 + getStageDifficulty(chapterIndex, stageInChapter);
  const getBossHpMultiplier = (chapterIndex, stageInChapter) => stageInChapter === 10 ? 1 + getStageDifficulty(chapterIndex, stageInChapter) + .3 : 1;
  const getChapterFireIntervalBase = (chapterIndex) => chapterIndex === 0 ? 1.2 : (CHAPTER_ENEMY_FIRE_INTERVAL_BASE[chapterIndex] || 1);
  function getEnemyFireInterval(chapterIndex, enemyType) { const config = ENEMY_TYPE_CONFIG[enemyType]; return !config?.canFire ? null : Math.max(.35, Number((getChapterFireIntervalBase(chapterIndex) * config.fireIntervalMultiplier).toFixed(2))); }
  const getEnemyFirstFireDelay = (enemyType) => ENEMY_TYPE_CONFIG[enemyType]?.canFire ? ENEMY_TYPE_CONFIG[enemyType].firstFireDelay : null;
  function normalizeComposition(composition) { const total = Object.values(composition).reduce((sum, value) => sum + value, 0); return total <= 0 ? { small: 1, shooter: 0, charger: 0, shield: 0, elite: 0 } : Object.fromEntries(Object.entries(composition).map(([key, value]) => [key, Number((value / total).toFixed(4))])); }
  function getStageEnemyComposition(chapterIndex, stageInChapter) { if (chapterIndex === 0) return normalizeComposition(PROLOGUE_STAGE_CONFIG[stageInChapter]?.composition || { small: 1 }); if (chapterIndex === 7 && CHAPTER_7_COMPOSITION_OVERRIDE[stageInChapter]) return normalizeComposition(CHAPTER_7_COMPOSITION_OVERRIDE[stageInChapter]); return normalizeComposition(STAGE_COMPOSITION_TEMPLATE[getStageTemplateType(stageInChapter)]); }
  const getStageEnemyCount = (chapterIndex, stageInChapter) => chapterIndex === 0 ? (PROLOGUE_STAGE_CONFIG[stageInChapter]?.enemyCount || 0) : Math.ceil((BASE_STAGE_ENEMY_COUNT_TEMPLATE[stageInChapter] || 30) * (1 + getStageDifficulty(chapterIndex, stageInChapter) * .25));
  function getStageEnemySpawnPlan(chapterIndex, stageInChapter) { const totalEnemyCount = getStageEnemyCount(chapterIndex, stageInChapter); const composition = getStageEnemyComposition(chapterIndex, stageInChapter); const enemyCounts = {}; let assigned = 0; ["small", "shooter", "charger", "shield", "elite"].forEach((type, index, all) => { const count = index === all.length - 1 ? Math.max(0, totalEnemyCount - assigned) : Math.floor(totalEnemyCount * (composition[type] || 0)); enemyCounts[type] = count; assigned += count; }); return { totalEnemyCount, enemyCounts, composition }; }
  function getEnemyFinalStats({ chapterIndex, stageInChapter, enemyType }) { const config = ENEMY_TYPE_CONFIG[enemyType]; if (!config) throw new Error(`Unknown enemy type: ${enemyType}`); const hpMultiplier = enemyType === "boss" ? getBossHpMultiplier(chapterIndex, stageInChapter) : getStageEnemyHpMultiplier(chapterIndex, stageInChapter); const damageReductionRate = clamp(getStageDamageReductionRate(chapterIndex, stageInChapter) + (config.extraDamageReductionRate || 0), 0, .9); return { ...config, hp: Math.ceil(config.baseHp * hpMultiplier), firstFireDelay: getEnemyFirstFireDelay(enemyType), fireInterval: getEnemyFireInterval(chapterIndex, enemyType), damageReductionRate, damageTakenMultiplier: 1 - damageReductionRate }; }
  function getStageConfig(chapterIndex, stageInChapter) { const hasBoss = chapterIndex !== 0 && stageInChapter === 10; return { stageId: getStageId(chapterIndex, stageInChapter), chapterIndex, stageInChapter, previousStageId: getPreviousStageId(chapterIndex, stageInChapter), battleEndSeconds: 90, bossAppearSeconds: hasBoss ? 60 : null, difficulty: getStageDifficulty(chapterIndex, stageInChapter), damageReductionRate: getStageDamageReductionRate(chapterIndex, stageInChapter), enemyHpMultiplier: getStageEnemyHpMultiplier(chapterIndex, stageInChapter), hasBoss, boss: hasBoss ? { stats: getEnemyFinalStats({ chapterIndex, stageInChapter, enemyType: "boss" }), appearSeconds: 60, burstAttack: BOSS_BURST_ATTACK_CONFIG } : null, spawnPlan: getStageEnemySpawnPlan(chapterIndex, stageInChapter) }; }
  function generateAllStageConfigs() { const stages = []; for (let stage = 1; stage <= 3; stage += 1) stages.push(getStageConfig(0, stage)); for (let chapter = 1; chapter <= 9; chapter += 1) for (let stage = 1; stage <= 10; stage += 1) stages.push(getStageConfig(chapter, stage)); return stages; }
  const api = { STAGE_STRUCTURE_CONFIG, CHAPTER_ENEMY_FIRE_INTERVAL_BASE, ENEMY_FIRE_INTERVAL_LIMIT, ENEMY_TYPE_CONFIG, BOSS_BURST_ATTACK_CONFIG, PROLOGUE_STAGE_CONFIG, STAGE_DIFFICULTY_TEMPLATE, BASE_STAGE_ENEMY_COUNT_TEMPLATE, STAGE_COMPOSITION_TEMPLATE, CHAPTER_7_STAGE_DAMAGE_REDUCTION, CHAPTER_7_COMPOSITION_OVERRIDE, clamp, getStageId, getPreviousStageId, isStageUnlocked, getChapterDifficultyBase, getStageTemplateType, getStageDifficulty, getStageDamageReductionRate, getStageEnemyHpMultiplier, getBossHpMultiplier, getChapterFireIntervalBase, getEnemyFireInterval, getEnemyFirstFireDelay, getStageEnemyCount, normalizeComposition, getStageEnemyComposition, getStageEnemySpawnPlan, getEnemyFinalStats, getStageConfig, generateAllStageConfigs };
  scope.enemyStageBalance = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
